[tool.ruff]
target-version = "py38"
line-length = 120
lint.extend-select = ["RUF100"]

# imported but unused
[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
doctest_optionflags = "NORMALIZE_WHITESPACE"
